### ISSUE TITLE
БЗЪЪЪЪЪЪЪЪ

### ISSUE THREAD

**Issue by Agressive-Bz** [PAP6/AUM#8]
Предлагаю вам вернуться в Дискорд, пожалуйста

**Comment by Agressive-Bz** [comment]
Хд

**Comment by QBMC-server** [comment]
+++

**Comment by PAP6** [comment]
ты тоже гнида

**Comment by QBMC-server** [comment]
Арсений

**Comment by PAP6** [comment]
сдохните все в страшных пуках

**Comment by Agressive-Bz** [comment]
Всё, ладно, я так понимаю, ты не вернёшься?

**Comment by PAP6** [comment]
из-за вас мне каждый день по несколько десятков раз звонят китайцы на 2 номер телефона

**Comment by PAP6** [comment]
умрите
